📝rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
And, add this method to the bottom of the file, right before the end that ends the class:

def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to customers_path
end


    📝Explaining This Code
    The rescue_from statement says that if an exception of the specified type occurs, call the catch_not_found method.

    The Rails.logger.debug statement writes an entry to the Rails log. You will see it in the console, and it is also written to the log/development.log file.

    The flash.alert statement takes the message from the exception and stores it in the flash object so that it can be displayed to the user.

    The redirect_to statement puts up the index page again, so that the user does not see that other error page.

